### ISSUE TITLE
Failure to order certificate for multiple domains

### ISSUE THREAD

**Issue by PreferLinux** [ffMathy/FluffySpoon.AspNet.EncryptWeMust#216]
https://github.com/ffMathy/FluffySpoon.AspNet.EncryptWeMust/blob/ab67a89d24f0c3518bde2ddc2345fb9ab5ff2361/src/FluffySpoon.AspNet.EncryptWeMust/Certes/LetsEncryptClient.cs#L109
```C#
var anyValid = challenges.Any(x => x.Status == ChallengeStatus.Valid);
var allInvalid = challenges.All(x => x.Status == ChallengeStatus.Invalid);

if (anyValid || allInvalid)
    break;
```
Surely the All / Any is around the wrong way here? Shouldn't it be when all challenges are valid, or any are invalid? On line 41 we have `var challengeContexts = await Task.WhenAll(allAuthorizations.Select(x => x.Http()));`, and looking at [Certes](https://github.com/fszlin/certes/blob/08bf850bbed9e026c718f56f1bcc454afafb4f92/src/Certes/Extensions/IAuthorizationContextExtensions.cs#L46) this is taking the first http-01 challenge for the authorization, and therefore each challenge represents an authorization. [All authorizations need  to be valid](https://www.rfc-editor.org/rfc/rfc8555.html#section-7.1.6) for the order to be valid. Therefore, this can exit before the order is valid.

I'm pretty sure this will be the cause of an exception I've been getting (my cert has four alternate names):
```
Certes.AcmeRequestException: Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/finalize/...
urn:ietf:params:acme:error:orderNotReady: Order's status ("pending") is not acceptable for finalization
```
After the exception happens I still get more challenge verification requests coming in, so obviously Let's Encrypt hasn't finished validating the order, also indicated as the order status being pending. If I retry issuing certificates (i.e. restart the server) a couple of times it manages to get the cert.

I haven't actually tested the suggested change. I also haven't looked at your unit tests in detail, but the [client tests](https://github.com/ffMathy/FluffySpoon.AspNet.EncryptWeMust/blob/master/src/FluffySpoon.AspNet.EncryptWeMust.Tests/LetsEncryptClientTests.cs) seem to only test with one domain – might be a good idea to add a test with a few.

**Comment by ffMathy** [comment]
That makes a lot of sense. Do you have time for a PR?

**Comment by PreferLinux** [comment]
It'll probably take me a few days to get around to it, but that should be no problem.
