### ISSUE TITLE
Main package missing after rename

### ISSUE THREAD

**Issue by willdean** [ffMathy/FluffySpoon.AspNet.EncryptWeMust#82]
It looks like the main core `FluffySpoon.AspNet.EncryptWeMust` package is not on Nuget - the dependent packages are there (Azure, etc) but not the main one.

**Comment by ffMathy** [comment]
Oh, damn. Yeah we recently renamed everything due to a trademark violation :( Let me have a look.

**Comment by willdean** [comment]
Yes, I wondered how long you'd keep the name after That Other Library had to change theirs...

**Comment by ffMathy** [comment]
Fixed. Give it around 30 minutes and it should be live :)

**Comment by ffMathy** [comment]
Yeah... Quite silly.

**Comment by ffMathy** [comment]
By the way @willdean - want to be come an official contributor on this? I could use some help, since I don't have much time, and you've made really high quality contributions.

**Comment by willdean** [comment]
Hi @ffMathy - thanks for the offer - I'm not sure I'd be any more useful as a proper contributor, but I'm happy to try to help if you want to tag me on issues which come in.  I don't always have much free time, but time can sometimes be found for interesting things...
